version: "3.8"

services:
  flask_graphql:
    build: .
    container_name: flask_graphql
    environment:
      - FLASK_APP=main.py
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      PGDATA: /data/postgres
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
      - flask_graphql